name: lico_app
description: licc_app

version: 1.5.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.2
  sqflite: ^1.1.0
  dio: ^2.1.0
  json_annotation: ^2.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0
  json_serializable: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/flower.jpg
    - images/flower2.jpg
